# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-03 03:24
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0025_auto_20150710_0059'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='pagecategory',
            managers=[
                ('_default_manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
