# Generated by Django 2.1.2 on 2018-11-10 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0026_auto_20160202_2224'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='pagecategory',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='license',
            name='genericlink_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='website.GenericLink'),
        ),
    ]
